load("@buildifier_prebuilt//:rules.bzl", "buildifier")

exports_files([
    "defs.bzl",
    "extensions.bzl",
    "rules.bzl",
])

buildifier(
    name = "buildifier.fix",
    exclude_patterns = [
        "./.git/**/*",
    ],
    lint_mode = "fix",
    mode = "fix",
)

buildifier(
    name = "buildifier.check",
    exclude_patterns = [
        "./.git/**/*",
    ],
    lint_mode = "warn",
    mode = "check",
)
