module(name = "rules_periphery_smoke")

bazel_dep(name = "rules_periphery", version = "0.0.0")
local_path_override(
    module_name = "rules_periphery",
    path = "../../..",
)

periphery = use_extension("@rules_periphery//:extensions.bzl", "periphery")
periphery.local_binary(path = "/bin/echo")
use_repo(periphery, "periphery_generated")
